name: 'QA check with repoman'
on: [push, pull_request]
jobs:
    repoman:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: rafspiny/repoman-repo-qa@v2.1
